name: CompareGenome
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - biopython
  - r-base
  - r-factoextra
  - r-agricolae
  - r-seqinr
  - r-gplots
  - r-rmisc
  - r-phangorn
  - r-ggrepel
  - r-cowplot
  - bioconductor-biobase
  - bioconductor-ggtree
